maxInt = 1000
minInt = -1000

def devideIfNonZero(i, i2):
    if i == 0 or i2 == 0:
        return 'NAN'
    else:
        return str(i/i2)
    

txtfile = open("./calculator.py", "w")

txtfile.write("###This was my first calculator so please dont judge too hard \n###TODO: Make Work With FloatingPoints and Doubbles\n")
txtfile.write(f"print('This calculator only works for whole numbers from {minInt} to {maxInt}')\n")
txtfile.write("numOne = input('NumOne') \nsign = input('Sign') \nnumTwo = input('NumTwo') \n")

for i in range(minInt,maxInt):
    for i2 in range(minInt,maxInt):
        txtfile.write(f'''
if numOne == '{i}' and sign == '+' and numTwo == '{i2}':
    print('{i} + {i2} = {i + i2}')
if numOne == '{i}' and sign == '-' and numTwo == '{i2}':
    print('{i} - {i2} = {i - i2}')
if numOne == '{i}' and sign == '*' and numTwo == '{i2}':
    print('{i} * {i2} = {i * i2}')
if numOne == '{i}' and sign == '/' and numTwo == '{i2}':
    print('{i} / {i2} = {devideIfNonZero(i,i2)}')''')
txtfile.write("###Generated by 7th's calculator generator for idiots \n")    
txtfile.close()
